name: Create and publish a package
on:
  push:
    branches: [ develop, feature-release ]
  pull_request:
    branches: [ develop ]
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}      
    - name: Create a GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}      
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/web-image
        tags: latest,${{ steps.tag_version.outputs.new_tag }}
  docker-build:
    runs-on: ubuntu-latest
    needs: [build-and-push-image]
    steps:    
    - name: docker rebuild
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd app/
          echo docker login
          sudo docker login https://docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          echo docker pull
          sudo docker pull docker.pkg.github.com/joaquinceballos/escuelas-escalada-web/web-image:latest
          echo docker stop container
          sudo docker container stop contenedor-web-escuelas
          echo docker remove container
          sudo docker container rm contenedor-web-escuelas
          echo docker run
          sudo docker run -p 443:443 -p 80:80 -v /home/ubuntu/app/server.conf:/etc/nginx/conf.d/server.conf -v /home/ubuntu/app/certs:/certs --name contenedor-web-escuelas -d docker.pkg.github.com/joaquinceballos/escuelas-escalada-web/web-image
          echo fin
        host: ${{ secrets.WEB_HOST }}
        user: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        args: "-tt -vvv"          